data:
  batch_size: 64
  num_workers: 0
  data_dir: "../data"

model:
  learning_rate: 0.001

training:
  max_epochs: 5
  accelerator: "auto"
  early_stopping_patience: 3

logging:
  experiment_name: "mnist_classification"
  tracking_uri: "file:./mlruns"
  log_level: "INFO" 