data:
  batch_size: 512
  num_workers: 0
  train_val_split: 0.8
  paths:
    root: "./data"
    train: "./data/mnist/train"
    test: "./data/mnist/test"
    cache: "./data/mnist/cache"
  preprocessing:
    normalize: true
    augment: false
    cache_processed: true

model:
  learning_rate: 0.001
  hidden_size: 128

training:
  max_epochs: 3
  early_stopping_patience: 3
  accelerator: "auto"
  debug: true
  fast_dev_run: false

logging:
  experiment_name: "mnist_classification_dev"
  tracking_uri: "file:./mlruns"
  log_every_n_steps: 50
  log_level: "DEBUG" 