data:
  batch_size: 1024
  num_workers: 4
  train_val_split: 0.8
  paths:
    root: "/mnt/data/mnist"
    train: "/mnt/data/mnist/train"
    test: "/mnt/data/mnist/test"
    cache: "/mnt/data/mnist/cache"
  preprocessing:
    normalize: true
    augment: true
    cache_processed: true

model:
  learning_rate: 0.001
  hidden_size: 256

training:
  max_epochs: 50
  early_stopping_patience: 5
  accelerator: "gpu"
  debug: false
  fast_dev_run: false

logging:
  experiment_name: "mnist_classification_prod"
  tracking_uri: "http://mlflow-server:5000"
  log_every_n_steps: 100
  log_level: "INFO" 