data:
  batch_size: 32
  num_workers: 0
  train_val_split: 0.8
  paths:
    root: "./tests/data"
    train: "./tests/data/mnist/train"
    test: "./tests/data/mnist/test"
    cache: "./tests/data/mnist/cache"
  preprocessing:
    normalize: true
    augment: false
    cache_processed: false

model:
  learning_rate: 0.001
  hidden_size: 64

training:
  max_epochs: 1
  early_stopping_patience: 1
  accelerator: "cpu"
  debug: true
  fast_dev_run: true

logging:
  experiment_name: "mnist_classification_test"
  tracking_uri: "file:./tests/mlruns"
  log_every_n_steps: 1
  log_level: "DEBUG" 