apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml

commonLabels:
  app.kubernetes.io/part-of: mnist-classification
  app.kubernetes.io/managed-by: kustomize 